// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdqviU9mX084qvZpPEb6m8uH2PKK26B90',
    appId: '1:509644587435:web:f5879dd302750723e9d2ee',
    messagingSenderId: '509644587435',
    projectId: 'financeapplication-3dad5',
    authDomain: 'financeapplication-3dad5.firebaseapp.com',
    storageBucket: 'financeapplication-3dad5.firebasestorage.app',
    measurementId: 'G-YYJSXSTM6R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_QnBH34RxM0hMgRyUY1s1KiD6IrOULW8',
    appId: '1:509644587435:android:c38a26ef2cf847bae9d2ee',
    messagingSenderId: '509644587435',
    projectId: 'financeapplication-3dad5',
    storageBucket: 'financeapplication-3dad5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBa2BE_nEpeuspiuibPneDj8F0dOaNg4lY',
    appId: '1:509644587435:ios:a07d706eb4e41229e9d2ee',
    messagingSenderId: '509644587435',
    projectId: 'financeapplication-3dad5',
    storageBucket: 'financeapplication-3dad5.firebasestorage.app',
    iosClientId: '509644587435-g886hnqr7i9jrhfh9cd43lrt8urla17k.apps.googleusercontent.com',
    iosBundleId: 'com.example.personalFinanceApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBa2BE_nEpeuspiuibPneDj8F0dOaNg4lY',
    appId: '1:509644587435:ios:a07d706eb4e41229e9d2ee',
    messagingSenderId: '509644587435',
    projectId: 'financeapplication-3dad5',
    storageBucket: 'financeapplication-3dad5.firebasestorage.app',
    iosClientId: '509644587435-g886hnqr7i9jrhfh9cd43lrt8urla17k.apps.googleusercontent.com',
    iosBundleId: 'com.example.personalFinanceApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdqviU9mX084qvZpPEb6m8uH2PKK26B90',
    appId: '1:509644587435:web:b57318668bba6c93e9d2ee',
    messagingSenderId: '509644587435',
    projectId: 'financeapplication-3dad5',
    authDomain: 'financeapplication-3dad5.firebaseapp.com',
    storageBucket: 'financeapplication-3dad5.firebasestorage.app',
    measurementId: 'G-PQ4TY9YF7Y',
  );
}
